In [1]:
import numpy as np
print('numpy: %s' % np.__version__)

import pandas as pd
print('pandas: %s' % pd.__version__)

import tensorflow as tf
print('tensorflow: %s' % tf.__version__)

import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
print('sklearn: %s' % sklearn.__version__)

import matplotlib
import matplotlib.pyplot as plt
print('matplotlib: %s' % matplotlib.__version__)

numpy: 1.19.5
pandas: 1.3.1
tensorflow: 2.6.0
sklearn: 0.24.2
matplotlib: 3.4.2

In [2]:
# Display all the columns for the dataframes (not-truncated)
pd.set_option("display.max_columns", None)

## Load the CSV

In [3]:
#  Import and read the charity_data.csv
application_df = pd.read_csv("Resources/clean_charity_data.csv")
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

* **APPLICATION_TYPE**â€”Alphabet Soup application type
* **AFFILIATION**â€”Affiliated sector of industry
* **CLASSIFICATION**â€”Government organization classification
* **USE_CASE**â€”Use case for funding
* **ORGANIZATION**â€”Organization type
* **STATUS**â€”Active status
* **INCOME_AMT**â€”Income classification
* **SPECIAL_CONSIDERATIONS**â€”Special consideration for application
* **ASK_AMT**â€”Funding amount requested
* **IS_SUCCESSFUL**â€”Was the money used effectively

In [4]:
# Split the columns into quantitative and categorical
all_quantitative_columns = set(application_df.describe().columns)
all_categorical_columns = set(application_df.columns) - all_quantitative_columns
print("quantitative columns\n\t" + "\n\t".join(all_quantitative_columns))
print()
print("categorical columns\n\t" + "\n\t".join(all_categorical_columns))

quantitative columns
	IS_SUCCESSFUL
	ASK_AMT
	STATUS

categorical columns
	AFFILIATION
	APPLICATION_TYPE
	USE_CASE
	INCOME_AMT
	ORGANIZATION
	SPECIAL_CONSIDERATIONS
	CLASSIFICATION

In [5]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df, columns=all_categorical_columns)
application_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,AFFILIATION_CompanySponsored,AFFILIATION_Family/Parent,AFFILIATION_Independent,AFFILIATION_National,AFFILIATION_Other,AFFILIATION_Regional,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,APPLICATION_TYPE_T8,USE_CASE_CommunityServ,USE_CASE_Heathcare,USE_CASE_Other,USE_CASE_Preservation,USE_CASE_ProductDev,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,CLASSIFICATION_C1000,CLASSIFICATION_C1200,CLASSIFICATION_C2000,CLASSIFICATION_C2100,CLASSIFICATION_C3000,CLASSIFICATION_Other
0,1,5000,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0
1,1,108590,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0
2,1,5000,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0
3,1,6692,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0
4,1,142590,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0
34295,1,5000,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0
34296,1,5000,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0
34297,1,5000,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0

In [6]:
# shuffle our data to remove any potential bias
application_df = sklearn.utils.shuffle(application_df)

In [7]:
# Split our preprocessed data into our features and target arrays
target_feature = "IS_SUCCESSFUL"

X = application_df.drop(columns=[target_feature])
y = application_df[target_feature].values.ravel()
print(X.shape, y.shape)

(34299, 43) (34299,)

In [8]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)
print("train\t", X_train.shape, y_train.shape)
print("test\t", X_test.shape, y_test.shape)

train	 (25724, 43) (25724,)
test	 (8575, 43) (8575,)

In [9]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [10]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_shape=(len(X_train_scaled[0]),)
hidden_layers = [
    80, 
    30, 
    1,
]

nn = tf.keras.models.Sequential()
nn.add(tf.keras.Input(shape=input_shape))
for layer in hidden_layers:
    nn.add(tf.keras.layers.Dense(layer))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 80)                3520
_________________________________________________________________
dense_1 (Dense)              (None, 30)                2430
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 31
=================================================================
Total params: 5,981
Trainable params: 5,981
Non-trainable params: 0
_________________________________________________________________

In [11]:
# Compile the model
nn.compile(
    optimizer = "Adam", 
    loss = "mse", 
    metrics = ["mae"]
)

In [12]:
# Train the model
history = nn.fit(
    X_train_scaled, 
    y_train, 
    epochs = 100
)
history.params

Epoch 1/100
804/804 [==============================] - 1s 955us/step - loss: 0.4451 - mae: 0.4172
Epoch 2/100
804/804 [==============================] - 1s 900us/step - loss: 0.3287 - mae: 0.4010
Epoch 3/100
804/804 [==============================] - 1s 922us/step - loss: 0.2374 - mae: 0.3997
Epoch 4/100
804/804 [==============================] - 1s 890us/step - loss: 0.2127 - mae: 0.3961
Epoch 5/100
804/804 [==============================] - 1s 918us/step - loss: 0.2844 - mae: 0.4011
Epoch 6/100
804/804 [==============================] - 1s 967us/step - loss: 0.2315 - mae: 0.3984
Epoch 7/100
804/804 [==============================] - 1s 963us/step - loss: 0.2000 - mae: 0.3947
Epoch 8/100
804/804 [==============================] - 1s 963us/step - loss: 0.2024 - mae: 0.3957
Epoch 9/100
804/804 [==============================] - 1s 974us/step - loss: 0.2064 - mae: 0.3970
Epoch 10/100
804/804 [==============================] - 1s 974us/step - loss: 0.2064 - mae: 0.3968
Epoch 11/100
804/804 [==============================] - 1s 977us/step - loss: 0.2015 - mae: 0.3958
Epoch 12/100
804/804 [==============================] - 1s 951us/step - loss: 0.2036 - mae: 0.3964
Epoch 13/100
804/804 [==============================] - 1s 938us/step - loss: 0.2014 - mae: 0.3946
Epoch 14/100
804/804 [==============================] - 1s 973us/step - loss: 0.2001 - mae: 0.3950
Epoch 15/100
804/804 [==============================] - 1s 981us/step - loss: 0.1980 - mae: 0.3943
Epoch 16/100
804/804 [==============================] - 1s 987us/step - loss: 0.1987 - mae: 0.3947
Epoch 17/100
804/804 [==============================] - 1s 968us/step - loss: 0.1980 - mae: 0.3939
Epoch 18/100
804/804 [==============================] - 1s 968us/step - loss: 0.1976 - mae: 0.3942
Epoch 19/100
804/804 [==============================] - 1s 953us/step - loss: 0.1983 - mae: 0.3946
Epoch 20/100
804/804 [==============================] - 1s 943us/step - loss: 0.1975 - mae: 0.3942
Epoch 21/100
804/804 [==============================] - 1s 939us/step - loss: 0.1974 - mae: 0.3945
Epoch 22/100
804/804 [==============================] - 1s 976us/step - loss: 0.1972 - mae: 0.3938
Epoch 23/100
804/804 [==============================] - 1s 1ms/step - loss: 0.1968 - mae: 0.3932
Epoch 24/100
804/804 [==============================] - 1s 953us/step - loss: 0.1969 - mae: 0.3939
Epoch 25/100
804/804 [==============================] - 1s 1ms/step - loss: 0.1971 - mae: 0.3938
Epoch 26/100
804/804 [==============================] - 1s 963us/step - loss: 0.1969 - mae: 0.3938
Epoch 27/100
804/804 [==============================] - 1s 936us/step - loss: 0.1969 - mae: 0.3939
Epoch 28/100
804/804 [==============================] - 1s 952us/step - loss: 0.1966 - mae: 0.3937
Epoch 29/100
804/804 [==============================] - 1s 939us/step - loss: 0.1968 - mae: 0.3936
Epoch 30/100
804/804 [==============================] - 1s 950us/step - loss: 0.1968 - mae: 0.3938
Epoch 31/100
804/804 [==============================] - 1s 972us/step - loss: 0.1966 - mae: 0.3937
Epoch 32/100
804/804 [==============================] - 1s 945us/step - loss: 0.1968 - mae: 0.3942
Epoch 33/100
804/804 [==============================] - 1s 935us/step - loss: 0.1967 - mae: 0.3935
Epoch 34/100
804/804 [==============================] - 1s 929us/step - loss: 0.1966 - mae: 0.3937
Epoch 35/100
804/804 [==============================] - 1s 957us/step - loss: 0.1968 - mae: 0.3937
Epoch 36/100
804/804 [==============================] - 1s 968us/step - loss: 0.1964 - mae: 0.3932
Epoch 37/100
804/804 [==============================] - 1s 950us/step - loss: 0.1965 - mae: 0.3935
Epoch 38/100
804/804 [==============================] - 1s 974us/step - loss: 0.1965 - mae: 0.3936
Epoch 39/100
804/804 [==============================] - 1s 934us/step - loss: 0.1966 - mae: 0.3939
Epoch 40/100
804/804 [==============================] - 1s 938us/step - loss: 0.1962 - mae: 0.3928
Epoch 41/100
804/804 [==============================] - 1s 940us/step - loss: 0.1965 - mae: 0.3938
Epoch 42/100
804/804 [==============================] - 1s 948us/step - loss: 0.1964 - mae: 0.3935
Epoch 43/100
804/804 [==============================] - 1s 931us/step - loss: 0.1964 - mae: 0.3932
Epoch 44/100
804/804 [==============================] - 1s 958us/step - loss: 0.1963 - mae: 0.3931
Epoch 45/100
804/804 [==============================] - 1s 935us/step - loss: 0.1963 - mae: 0.3935
Epoch 46/100
804/804 [==============================] - 1s 965us/step - loss: 0.1963 - mae: 0.3933
Epoch 47/100
804/804 [==============================] - 1s 965us/step - loss: 0.1962 - mae: 0.3930
Epoch 48/100
804/804 [==============================] - 1s 1ms/step - loss: 0.1964 - mae: 0.3933
Epoch 49/100
804/804 [==============================] - 1s 933us/step - loss: 0.1962 - mae: 0.3933
Epoch 50/100
804/804 [==============================] - 1s 1ms/step - loss: 0.1961 - mae: 0.3933
Epoch 51/100
804/804 [==============================] - 1s 1ms/step - loss: 0.1962 - mae: 0.3930
Epoch 52/100
804/804 [==============================] - 1s 1ms/step - loss: 0.1963 - mae: 0.3930
Epoch 53/100
804/804 [==============================] - 1s 991us/step - loss: 0.1962 - mae: 0.3933
Epoch 54/100
804/804 [==============================] - 1s 1ms/step - loss: 0.1963 - mae: 0.3932
Epoch 55/100
804/804 [==============================] - 1s 1ms/step - loss: 0.1963 - mae: 0.3934
Epoch 56/100
804/804 [==============================] - 1s 1ms/step - loss: 0.1961 - mae: 0.3930
Epoch 57/100
804/804 [==============================] - 1s 1ms/step - loss: 0.1962 - mae: 0.3929
Epoch 58/100
804/804 [==============================] - 1s 1ms/step - loss: 0.1960 - mae: 0.3929
Epoch 59/100
804/804 [==============================] - 1s 878us/step - loss: 0.1961 - mae: 0.3930
Epoch 60/100
804/804 [==============================] - 1s 938us/step - loss: 0.1962 - mae: 0.3933
Epoch 61/100
804/804 [==============================] - 1s 940us/step - loss: 0.1962 - mae: 0.3931
Epoch 62/100
804/804 [==============================] - 1s 911us/step - loss: 0.1962 - mae: 0.3932
Epoch 63/100
804/804 [==============================] - 1s 896us/step - loss: 0.1961 - mae: 0.3932
Epoch 64/100
804/804 [==============================] - 1s 1ms/step - loss: 0.1961 - mae: 0.3931
Epoch 65/100
804/804 [==============================] - 1s 935us/step - loss: 0.1961 - mae: 0.3928
Epoch 66/100
804/804 [==============================] - 1s 916us/step - loss: 0.1962 - mae: 0.3932
Epoch 67/100
804/804 [==============================] - 1s 924us/step - loss: 0.1963 - mae: 0.3932
Epoch 68/100
804/804 [==============================] - 1s 902us/step - loss: 0.1961 - mae: 0.3929
Epoch 69/100
804/804 [==============================] - 1s 913us/step - loss: 0.1961 - mae: 0.3932
Epoch 70/100
804/804 [==============================] - 1s 866us/step - loss: 0.1961 - mae: 0.3927
Epoch 71/100
804/804 [==============================] - 1s 873us/step - loss: 0.1961 - mae: 0.3934
Epoch 72/100
804/804 [==============================] - 1s 873us/step - loss: 0.1960 - mae: 0.3925
Epoch 73/100
804/804 [==============================] - 1s 930us/step - loss: 0.1960 - mae: 0.3931
Epoch 74/100
804/804 [==============================] - 1s 928us/step - loss: 0.1961 - mae: 0.3929
Epoch 75/100
804/804 [==============================] - 1s 1ms/step - loss: 0.1961 - mae: 0.3932
Epoch 76/100
804/804 [==============================] - 1s 1ms/step - loss: 0.1962 - mae: 0.3931
Epoch 77/100
804/804 [==============================] - 1s 1ms/step - loss: 0.1961 - mae: 0.3928
Epoch 78/100
804/804 [==============================] - 1s 891us/step - loss: 0.1961 - mae: 0.3932
Epoch 79/100
804/804 [==============================] - 1s 945us/step - loss: 0.1961 - mae: 0.3929
Epoch 80/100
804/804 [==============================] - 1s 1ms/step - loss: 0.1962 - mae: 0.3930
Epoch 81/100
804/804 [==============================] - 1s 2ms/step - loss: 0.1962 - mae: 0.3933
Epoch 82/100
804/804 [==============================] - 1s 1ms/step - loss: 0.1961 - mae: 0.3932
Epoch 83/100
804/804 [==============================] - 1s 965us/step - loss: 0.1961 - mae: 0.3928
Epoch 84/100

804/804 [==============================] - 1s 903us/step - loss: 0.1962 - mae: 0.3929
Epoch 85/100
804/804 [==============================] - 1s 943us/step - loss: 0.1960 - mae: 0.3929
Epoch 86/100
804/804 [==============================] - 1s 1ms/step - loss: 0.1961 - mae: 0.3933
Epoch 87/100
804/804 [==============================] - 1s 991us/step - loss: 0.1960 - mae: 0.3929
Epoch 88/100
804/804 [==============================] - 1s 979us/step - loss: 0.1961 - mae: 0.3930
Epoch 89/100
804/804 [==============================] - 1s 986us/step - loss: 0.1960 - mae: 0.3930
Epoch 90/100
804/804 [==============================] - 1s 993us/step - loss: 0.1961 - mae: 0.3929
Epoch 91/100
804/804 [==============================] - 1s 989us/step - loss: 0.1960 - mae: 0.3928
Epoch 92/100
804/804 [==============================] - 1s 912us/step - loss: 0.1961 - mae: 0.3933
Epoch 93/100
804/804 [==============================] - 1s 956us/step - loss: 0.1959 - mae: 0.3927
Epoch 94/100
804/804 [==============================] - 1s 958us/step - loss: 0.1960 - mae: 0.3926
Epoch 95/100
804/804 [==============================] - 1s 915us/step - loss: 0.1961 - mae: 0.3933
Epoch 96/100
804/804 [==============================] - 1s 1ms/step - loss: 0.1959 - mae: 0.3923
Epoch 97/100
804/804 [==============================] - 1s 1ms/step - loss: 0.1961 - mae: 0.3933
Epoch 98/100
804/804 [==============================] - 1s 972us/step - loss: 0.1960 - mae: 0.3927
Epoch 99/100
804/804 [==============================] - 1s 939us/step - loss: 0.1960 - mae: 0.3929
Epoch 100/100
804/804 [==============================] - 1s 976us/step - loss: 0.1961 - mae: 0.3931

{'verbose': 1, 'epochs': 100, 'steps': 804}

In [13]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.1992 - mae: 0.3949
Loss: 0.19924820959568024, Accuracy: 0.3948777914047241

In [14]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_Optimization.h5")

## Load the saved model

In [15]:
loaded_model = tf.keras.models.load_model("AlphabetSoupCharity_Optimization.h5")
# Check its architecture
loaded_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 80)                3520
_________________________________________________________________
dense_1 (Dense)              (None, 30)                2430
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 31
=================================================================
Total params: 5,981
Trainable params: 5,981
Non-trainable params: 0
_________________________________________________________________

In [16]:
# Evaluate the loaded model using the test data
model_loss, model_accuracy = loaded_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.1992 - mae: 0.3949
Loss: 0.19924820959568024, Accuracy: 0.3948777914047241